name: Dev Workflow - Test and check thing
on:
  push:
    branches:
      - dev
jobs:
  pull:
    strategy:
      matrix:
        os: [self-hosted]
    
    runs-on: {{ matrix.os }}

    steps:
      - name: Pulls from remote dev
        run: |
          git pull origin dev
  
  build-and-test:
    needs:
      - pull
    
    strategy:
      matrix:
        os: [self-hosted]

    runs-on: {{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
  deploy:
    needs:
      - build-and-test

    strategy:
      matrix:
        os: [self-hosted]
    
    runs-on: {{ matrix.os }}

    steps:
    - name: Deploys the App
      run: |
        python app.py
