name: Master Workflow - Builds and tests the master branch
on:
  pull_request:
    types: closed
    branches:
      - master
jobs:
  pull:    
    runs-on: self-hosted

    steps:
      - name: Sets environment
        run: |
          echo "$HOME/scripts" >> $GITHUB_PATH
      
      - uses: actions/checkout@v2
      - name: Pulls from remote master
        run: |
          bash pull_repo.sh ${{ github.event.repository.name }} master
  
  build-and-test:
    needs:
      - pull

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
