name: Master Workflow - Build and deploy to production
on:
  pull_request:
    types: closed
    branches:
      - master
jobs:
  build-and-test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
  deploy:
    needs:
      - build-and-test
    
    runs-on: self.hosted

    steps:
    - name: Deploys the App
      run: |
        python app.py